### ISSUE TITLE
Fix image animations on homepage

### ISSUE THREAD

**Issue by schooltape** [schooltape-community/schooltape-community.github.io#2]

**Comment by FairyPenguin** [comment]
Hey, 
I can work on this, but from what I get by scrolling through the website, there are other issues already there and the website needs a lot of improvements.

So, if you would like I can work on improving the website UI&UX and add some improvements for the long-term not just fix the animations.

**Comment by schooltape** [comment]
> Hey, I can work on this, but from what I get by scrolling through the website, there are other issues already there and the website needs a lot of improvements.
> 
> So, if you would like I can work on improving the website UI&UX and add some improvements for the long-term not just fix the animations.

Sure, only if you have time and want to though. This is just a small project I'm spending an hour or so on per week - and the website isn't of much importance.

And yes, I agree the UI is pretty average.. I just started learning _very_ basic web dev.

Thanks

**Comment by 42Willow** [comment]
The animations were screwed because I had to use CSS to implement them for a rubric. I've fixed them in the latest commit.
